language: node_js
branches:
  only:
    - gh-pages
env:
  global:
    - URL="https://w3c.github.io/payment-handler/echidna-manifest.txt"
    - DECISION="https://www.w3.org/2016/04/14-wpwg-minutes#item02"
    - secure: T01htxjsjo0H88sUL6gXcqdL8p1Fcrl7HIq83qoE+LcGGo+x7qwJAl5p4Ld3yLKt45o/Dqk0qTynwrNlacB3Wzgnt0D1y+ukOgpIhv6ivDXzUe9vD9SZiDrTkig+yFYPhi6Sl3Hu1lB7L2H3Bz7LRsevVu6Hd2YLySkqFRBlIGhHeQzfKN407lh1VuYWHPmBKwF/NuGienhb2GuFbs/Fo5EH8xBXSfGISOsRd8s4KGo7FdZ2SnTus4V73nO8xGKKYIdeOd2W8+2Yy213JVf7BsYlrFGGyTSgv/1BjqIv9Q2Yiq+zqfuHZgMYICOJPtJbgkVOTVcMk6xVLiztFbDhzMkwYIzCNGZCzsolc+WvR4ANX03vxpUswM19jcaWefnbh9Ndd9pKytwiidQUi27amNCIzMMTpJ4QNBGikhUSRNkz6RAUfuREzRF04wrjbJWzPWOXNGz6VxcohQqOo3Nlbfc+q7Wa1kIWXSUNzEq4C4jxYxmWNGQ77jrW8MWrcdV480Gp/zmdc5vswb2vV5x4XxJRWBIpNtgFjiUfgklS3f/9xbRXqjr8T753cRywPAiDMXglJTe5WzaJz3/sPYtS1VdMhCJOuMqayMHmbviu6Ii4Dl2hZwia2CrO9rjqgDpqEeDGpEKB08q3l4CAtqUezGCJgux2UVfWKNRkIO2QW1I=
script:
  - echo "ok"
after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
