name: Node CI

on:
  push:
    branches:
      - gh-pages
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/respec-w3c-auto-publish@v1 # use the action
        with:
          ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          ECHIDNA_MANIFEST_URL: "https://w3c.github.io/payment-handler/echidna-manifest.txt"
          WG_DECISION_URL: "https://www.w3.org/2016/04/14-wpwg-minutes#item02"
          CC: "${{ secrets.CC }}"
