name: CI
on:
  pull_request: {}
  push:
    branches: [gh-pages]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: "https://www.w3.org/2016/04/14-wpwg-minutes#item02"
          W3C_NOTIFICATIONS_CC: "${{ secrets.CC }}"
          W3C_BUILD_OVERRIDE: |
            shortName: payment-handler
            specStatus: WD
